GFORMS-2533: Add Conditional Validation to Schema
hmrc/gform pull request #1094
Opened 2024-02-07 09:38 UTC by Aashvin

2024-02-07 12:03 UTC, josef-vlach requested changes

2024-02-07 12:03 UTC, josef-vlach commented on conf/formTemplateSchema.json
> +              "not": {"required": ["infoText"]}
Would it be possible to format this? (applies to whole json)

My formatter do this for example:
```
              "not": {
                "required": [
                  "infoText"
                ]
              }
```

2024-02-07 12:21 UTC, lxol commented on app/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidator.scala
> +            NonEmptyList(conditionalValidationErrorMessages.head, conditionalValidationErrorMessages.tail)
is that possible that `conditionalValidationErrorMessages is empty?
Also you can use NonEmptyList.fromList method instead here or its unsafe version.

2024-02-07 12:23 UTC, lxol commented on app/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidator.scala
> +            NonEmptyList(conditionalValidationErrorMessages.head, conditionalValidationErrorMessages.tail)
also `errors` on line 65 is NonEmptyList and the final result is NonEmptyList. May be we should keep it as `Nel` and never convert it to list, to ensure non-emptiness?

2024-02-07 12:24 UTC, lxol commented on app/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidator.scala
> +            NonEmptyList(conditionalValidationErrorMessages.head, conditionalValidationErrorMessages.tail)
oops, just saw @josef-vlach comments about the same...

2024-02-09 09:13 UTC, josef-vlach requested changes

2024-02-09 09:13 UTC, josef-vlach commented on test/uk/gov/hmrc/gform/formtemplate/JsonSchemeValidatorSpec.scala
> +      objects = Map()
Can we replace all these parameters with actual json under test? Like:
```
json"""
  {
    "infoType": "noformat",
    "type": "text",
    "id": "testId",
    "label": "test label"
  }"""
```
That would make the tests really nice to read.

2024-02-09 15:25 UTC, josef-vlach approved these changes
Please use Squash and merge 🙏

2024-02-09 16:03 UTC, merged