GFORMS-2611: Allow a caption to be defined for a task and use this for all sections unless a caption is defined on section within task
hmrc/gform pull request #1136
Opened 2024-04-04 10:51 UTC by Aashvin

2024-04-04 13:59 UTC, josef-vlach requested changes

2024-04-04 13:59 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/formtemplate/Rewriter.scala
> +
Can we update only a caption and then call `updateClassicSection` to reduce duplication?

2024-04-05 09:15 UTC, josef-vlach requested changes

2024-04-05 09:15 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/builder/BuilderController.scala
> +
Please delete this if it is not needed

2024-04-05 09:22 UTC, Aashvin commented on app/uk/gov/hmrc/gform/builder/BuilderController.scala
> +
Apologies, deleted.

2024-04-05 09:34 UTC, josef-vlach approved these changes

2024-04-05 09:41 UTC, merged