GFORMS-2429 - Choice expression should be syntactic sugar for concat …
hmrc/gform pull request #1251
Opened 2024-11-19 09:44 UTC by jmartinhmrc

…expression internally

2024-11-19 11:05 UTC, josef-vlach requested changes

2024-11-19 11:05 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/core/parsers/ValueParser.scala
> +      ChoiceLabel(expr +: exprs)
```suggestion
    | "choice(" ~ FormComponentId.unanchoredIdValidation ~ ")" ^^ { case _ ~ value ~ _ =>
      Concat(FormCtx(FormComponentId(value)) :: Nil)
```

We should not change the parser.

We should remove `final case class ChoiceLabel(formComponentId: FormComponentId) extends Expr` altogether.

2024-11-20 09:39 UTC, josef-vlach requested changes

2024-11-20 09:39 UTC, josef-vlach commented on test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
> +import uk.gov.hmrc.gform.sharedmodel.formtemplate.{ TextExpression, _ }
This is unnecessary change.

2024-11-20 09:51 UTC, jmartinhmrc commented on test/uk/gov/hmrc/gform/core/parsers/ValueParserSpec.scala
> +import uk.gov.hmrc.gform.sharedmodel.formtemplate.{ TextExpression, _ }
Ah yeah - thanks

2024-11-20 09:57 UTC, josef-vlach approved these changes

2024-11-20 10:01 UTC, merged