GFORMS-791: Enhance choice component to allow for a text divider
hmrc/gform pull request #746
Opened 2022-03-21 14:21 UTC by lxol

2022-03-21 16:30 UTC, josef-vlach requested changes

2022-03-21 16:30 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ComponentType.scala
> +  dividerText: String = "or",
This cannot be `String` since `String` cannot be localised. Use `LocalisedString` instead.

2022-03-22 15:11 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ComponentType.scala
> +  dividerText: LocalisedString = LocalisedString(Map(LangADT.En -> "or", LangADT.Cy -> "neu")),
Is this default value needed?

2022-03-22 15:29 UTC, lxol commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/ComponentType.scala
> +  dividerText: LocalisedString = LocalisedString(Map(LangADT.En -> "or", LangADT.Cy -> "neu")),
no it is not needed. I refactored.

2022-03-22 15:32 UTC, josef-vlach approved these changes

2022-03-22 15:37 UTC, merged