GFORMS-1888 - Add a feature to allow a choice to redirect a user to a…
hmrc/gform pull request #817
Opened 2022-09-07 14:46 UTC by DursunGundogan

… url without opening a new tab

2022-09-08 08:53 UTC, josef-vlach requested changes

2022-09-08 08:53 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/formtemplate/Rewriter.scala
> +                redirects = s.page.redirects.map(_.map(r => r.copy(ifExpr = replaceIncludeIf(r.ifExpr))))
Can we introduce `replaceRedirects` method and reuse it?

This
```
page.redirects.map(_.map(r => r.copy(ifExpr = replaceIncludeIf(r.ifExpr))))
```
Is repeated 3x here 👎

2022-09-08 08:53 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/RedirectCtx.scala
> +  implicit val format: Format[RedirectCtx] = Format[RedirectCtx](reads, writes)
Same question as on frontend. What is the deal with nullability of `includeIf`?

2022-09-08 15:39 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/RedirectCtx.scala
> +  implicit val format: Format[RedirectCtx] = Format[RedirectCtx](reads, writes)
This cannot be derived?

2022-09-08 15:50 UTC, DursunGundogan commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/RedirectCtx.scala
> +  implicit val format: Format[RedirectCtx] = Format[RedirectCtx](reads, writes)
Yes, it can be derived. fixed

2022-09-09 09:25 UTC, josef-vlach approved these changes

2022-09-09 09:45 UTC, merged