GFORMS-2066 Add ability to have 2 dataRetrieve calls on 1 page and the 2nd be conditional on the first
hmrc/gform pull request #894
Opened 2023-02-17 15:10 UTC by lxol

2023-02-23 09:17 UTC, josef-vlach requested changes

2023-02-23 09:17 UTC, josef-vlach commented on app/uk/gov/hmrc/gform/sharedmodel/formtemplate/Page.scala
> +  dataRetrieve: List[DataRetrieve],
Lets represent this as `Option[NonEmptyList[DataRetrieve]]` And lets get rid of `withDefaultMissingField`

2023-02-24 10:28 UTC, lxol commented on app/uk/gov/hmrc/gform/sharedmodel/DataRetrieve.scala
> +    override val `if`: Option[IncludeIf] = None
I updated PR

2023-02-24 12:19 UTC, josef-vlach approved these changes

2023-02-24 12:42 UTC, merged